import { useRef, useState } from "react";
import { View } from "react-native";
import { MoviesCard, GamingCard } from "../../components/CardsComponents";
import {
  DrawerDivider,
  RowScrollView,
  ScreenScrollView,
  ScreenContainer,
  MixedFeedFlatList,
} from "../../components/ContainerComponents";
import { MovieIcon, GamingIcon } from "../../components/IconComponents";
import { OutlinedButton } from "../../components/PressableComponents";
import { BaseText } from "../../components/TextComponents";
import { useThemeContext } from "../../context/ThemeContext";
import { MainVideoFlatList } from "../../components/ContainerComponents";
import { useScrollToTopOnFocus } from "../../hooks/useScrollToTopOnFocus";
import { useSetVideoData } from "../../hooks/useSetVideoData";
import { styles } from "../../styles/styles";
import { navPaths } from "../../utils/constants";

export default function GamingScreen({ navigation }) {
  const { ctxColors, ctxFontSizes, ctxIconSizes } = useThemeContext();
  const scrollToTopRef = useRef(null);
  const [featuredGameVideos, setFeaturedGameVideos] = useState([]);
  const [shootingGameVideos, setSetShootingGameVideos] = useState([]);
  const [gameDeviceVideos, setGameDeviceVideos] = useState([]);
  const [fantasyGameVideos, setFantasyGameVideos] = useState([]);
  const [actionGameVideos, setActionGameVideos] = useState([]);
  const [isLoading, setIsLoading] = useState(true);

  useScrollToTopOnFocus(scrollToTopRef);
  useSetVideoData({
    query: "Featured Games",
    queryResults: 3,
    setVideos: setFeaturedGameVideos,
    setIsLoading,
  });
  useSetVideoData({
    query: "Shooting Games",
    queryResults: 5,
    setVideos: setSetShootingGameVideos,
    setIsLoading,
  });
  useSetVideoData({
    query: "Game Devices",
    queryResults: 3,
    setVideos: setGameDeviceVideos,
    setIsLoading,
  });
  useSetVideoData({
    query: "Fantasy Games",
    queryResults: 5,
    setVideos: setFantasyGameVideos,
    setIsLoading,
  });
  useSetVideoData({
    query: "Action Games",
    queryResults: 3,
    setVideos: setActionGameVideos,
    setIsLoading,
  });

  return (
    <ScreenContainer isLoading={isLoading} ref={scrollToTopRef}>
      <MixedFeedFlatList
        style={{ marginTop: 8 }}
        isLoading={isLoading}
        setIsLoading={setIsLoading}
        navigation={navigation}
        query={"Games"}
        ListHeaderComponent={
          <View
            style={[
              {marginBottom: 16, flexDirection: "row", alignItems: "center" },
              styles.screenPadLeft,
            ]}
          >
            <View
              style={{
                borderRadius: 99,
                padding: 10,
                backgroundColor: ctxColors.primary,
              }}
            >
              <GamingIcon size={ctxIconSizes.xl2} color={ctxColors.white} />
            </View>
            <BaseText
              style={{
                marginLeft: 10,
                fontSize: ctxFontSizes.xl2,
                fontWeight: "bold",
              }}
            >
              Gaming
            </BaseText>
          </View>
        }
        mixedData={[
          ...featuredGameVideos.slice(0, 3).map((video) => ({
            type: "mainVideo",
            data: video,
          })),
          {
            type: "gamingCards",
            data: shootingGameVideos,
            headerComponent: (
              <View
                style={[
                  {
                    marginBottom: 16,
                    flexDirection: "row",
                    justifyContent: "space-between",
                    alignItems: "center",
                  },
                  styles.screenPadHorizontal,
                ]}
              >
                <View>
                  <BaseText
                    style={{
                      fontWeight: "bold",
                    }}
                  >
                    Top Shooting Games
                  </BaseText>
                  <BaseText
                    style={{
                      fontSize: ctxFontSizes.xs,
                      fontWeight: "bold",
                      color: ctxColors.textSecondary,
                    }}
                  >
                    Auto-generated by YouTube
                  </BaseText>
                </View>
                <OutlinedButton>
                  <BaseText style={{ fontSize: ctxFontSizes.sm }}>
                    View All
                  </BaseText>
                </OutlinedButton>
              </View>
            ),
          },
          ...gameDeviceVideos.slice(0, 3).map((video) => ({
            type: "mainVideo",
            data: video,
          })),
          {
            type: "videoHorizontalPreview",
            data: fantasyGameVideos,
            headerComponent: (
              <View
                style={[
                  {
                    marginBottom: 16,
                    flexDirection: "row",
                    justifyContent: "space-between",
                    alignItems: "center",
                  },
                  styles.screenPadHorizontal,
                ]}
              >
                <View>
                  <BaseText
                    style={{
                      fontWeight: "bold",
                    }}
                  >
                    Fantasy Games
                  </BaseText>
                  <BaseText
                    style={{
                      fontSize: ctxFontSizes.xs,
                      fontWeight: "bold",
                      color: ctxColors.textSecondary,
                    }}
                  >
                    Fresh from the forest
                  </BaseText>
                </View>
                <OutlinedButton>
                  <BaseText style={{ fontSize: ctxFontSizes.sm }}>
                    View All
                  </BaseText>
                </OutlinedButton>
              </View>
            ),
          },
          ...actionGameVideos.slice(0, 3).map((video) => ({
            type: "mainVideo",
            data: video,
          })),
        ]}
      />
    </ScreenContainer>
  );
}
